// Code generated by crpc-protobuf-plugin. DO NOT EDIT.
// source: helloworld.proto

using System;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using CRpc.Async;
using CRpc.Rpc;
using CRpc.Rpc.CRpc.Codec;
using CRpc.Rpc.CRpc.Client;

namespace Example {

public abstract class GreeterClientBase : ICRpcGeneratedClient
{
    public IRpcClient __client = null!;

    public void BindRpcClient(IRpcClient client)
    {
        __client = client ?? throw new ArgumentNullException(nameof(client));
        client.RegisterPushHandler(1000, 2, __OnPushServerPushHelloAsync);
    }

    public async CRpcTask<(int, Example.HelloReply)> SayHelloAsync(Example.HelloRequest request, int timeOut = 5000)
    {
        CRpcMessage message = await __client.CallAsync(1000, 1, request.ToByteArray(), timeOut);
        var result = message.ResultCode;
        if (0 == result)
        {
            byte[] data = message.Body;
            return (0, Example.HelloReply.Parser.ParseFrom(data));
        }

        return (-1, null);
    }

    private async CRpcTask __OnPushServerPushHelloAsync(CRpcPushContext context, byte[] body)
    {
        await OnPushServerPushHelloAsync(context, Example.ServerHelloPush.Parser.ParseFrom(body));
    }

    protected virtual CRpcTask OnPushServerPushHelloAsync(CRpcPushContext context, Example.ServerHelloPush message)
    {
        return CRpcTask.CompletedTask(context.Loop);
    }

}
}
