// Code generated by crpc-protobuf-plugin. DO NOT EDIT.
// source: helloworld.proto

//#pragma warning disable 8607

using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using CRPC.Rpc;
using CRPC.Rpc.CRpc.Codec;
using CRPC.Rpc.CRpc.Client;

namespace Example {

public sealed class GreeterClient
{
    public IRpcClient __client;
    
    public async Task<(int, Example.HelloReply)> SayHelloAsync(Example.HelloRequest request, int timeOut = 5000)
    {
        CRpcMessage message = await __client.CallAsync(1000, 1, request.ToByteArray(), timeOut);
        var result = message.getHeader().getResultCode();
        if (0 == result)
        {
            byte[] data = message.getBody();
            return (0, Example.HelloReply.Parser.ParseFrom(data));
        }
        return (-1, null);
    }

}
}
