// Code generated by crpc-protobuf-plugin. DO NOT EDIT.
// source: helloworld.proto

using System;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using CRpc.Async;
using CRpc.Rpc;
using CRpc.Rpc.CRpc.Codec;
using CRpc.Rpc.CRpc.Server;

namespace Example {

public abstract class GreeterServiceBase : IRpcService, IRpcHttpJsonCodec
{
    public ushort GetServiceId()
    {
        return 1000;
    }

    public CRpcTask<(int, byte[])> OnMessageAsync(IRpcContext context, IRpcMessage req)
    {
        var rpcContext = (CRpcContext)context;
        var rpcReq = (CRpcMessage)req;
        var methodId = rpcReq.MethodId;
        if (methodId == 1) { return this.__OnMessageSayHelloAsync(rpcContext, rpcReq); }
        return CRpcTask.FromResult((-1, Array.Empty<byte>()));
    }

    public bool TryGetHttpMethodParsers(ushort methodId, out MessageParser requestParser, out MessageParser responseParser)
    {
        requestParser = null!;
        responseParser = null!;
        if (methodId == 1) { requestParser = Example.HelloRequest.Parser; responseParser = Example.HelloReply.Parser; return true; }
        return false;
    }

    private async CRpcTask<(int, byte[])> __OnMessageSayHelloAsync(CRpcContext context, CRpcMessage req)
    {
        var request = Example.HelloRequest.Parser.ParseFrom(req.Body);
        var (result, data) = await SayHelloAsync(context, request);
        var bytes = data.ToByteArray();
        return (result, bytes);
    }

    protected CRpcTask<bool> PushServerPushHelloAsync(CRpcConnection connection, Example.ServerHelloPush message)
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(message);
        return connection.SendPushAsync(1000, 2, message.ToByteArray());
    }

    // Please implement the following:
    protected abstract CRpcTask<(int, Example.HelloReply)> SayHelloAsync(CRpcContext context, Example.HelloRequest request);
}
}

