using System.Text;
using Google.Protobuf.Compiler;
using Google.Protobuf.Reflection;

namespace CRpcProtobufPlugin;

public static class CRpcGen
{
        public static void Generate(CodeGeneratorRequest request, CodeGeneratorResponse response)
        {
            foreach (var fileDescriptorProto in request.ProtoFile)
                try
                {
                    GenerateByProtoFile(fileDescriptorProto, response);
                }
                catch (Exception ex)
                {
                    using (Stream stream = File.Create("./error.txt"))
                    {
                        var err = Encoding.UTF8.GetBytes(ex.Message + ex.StackTrace);
                        stream.Write(err, 0, err.Length);
                    }

                    response.Error += ex.Message;
                }
        }

        private static void GenerateByProtoFile(FileDescriptorProto fileDescriptorProto, CodeGeneratorResponse response)
        {
            GenerateServer(fileDescriptorProto, response);
            GenerateClient(fileDescriptorProto, response);
        }

        private static void GenerateServer(FileDescriptorProto fileDescriptorProto, CodeGeneratorResponse response)
        {
            if (fileDescriptorProto.Service == null || fileDescriptorProto.Service.Count <= 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// Code generated by crpc-protobuf-plugin. DO NOT EDIT.");
            sb.AppendLine($"// source: {fileDescriptorProto.Name}");

            sb.AppendLine("");
            sb.AppendLine("using System;");
            sb.AppendLine("using Google.Protobuf;");
            sb.AppendLine("using Google.Protobuf.WellKnownTypes;");
            sb.AppendLine("using CRpc.Async;");
            sb.AppendLine("using CRpc.Rpc;");
            sb.AppendLine("using CRpc.Rpc.CRpc.Codec;");
            sb.AppendLine("using CRpc.Rpc.CRpc.Server;");
            sb.AppendLine("");

            var ns = GetFileNamespace(fileDescriptorProto);
            sb.AppendLine("namespace " + ns + " {");

            foreach (var serviceDescriptorProto in fileDescriptorProto.Service)
            {
                sb.AppendLine("");
                GenerateServiceForServer(serviceDescriptorProto, sb);
            }

            sb.AppendLine("}\n");

            var file = new CodeGeneratorResponse.Types.File
            {
                Name = GetFileName(fileDescriptorProto.Name) + "Service.cs",
                Content = sb.ToString()
            };
            response.File.Add(file);
        }

        private static void GenerateClient(FileDescriptorProto fileDescriptorProto, CodeGeneratorResponse response)
        {
            if (fileDescriptorProto.Service == null || fileDescriptorProto.Service.Count <= 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// Code generated by crpc-protobuf-plugin. DO NOT EDIT.");
            sb.AppendLine($"// source: {fileDescriptorProto.Name}");

            sb.AppendLine("");
            sb.AppendLine("using System;");
            sb.AppendLine("using Google.Protobuf;");
            sb.AppendLine("using Google.Protobuf.WellKnownTypes;");
            sb.AppendLine("using CRpc.Async;");
            sb.AppendLine("using CRpc.Rpc;");
            sb.AppendLine("using CRpc.Rpc.CRpc.Codec;");
            sb.AppendLine("using CRpc.Rpc.CRpc.Client;");
            sb.AppendLine("");

            var ns = GetFileNamespace(fileDescriptorProto);
            sb.AppendLine("namespace " + ns + " {");

            foreach (var serviceDescriptorProto in fileDescriptorProto.Service)
            {
                sb.AppendLine("");
                GenerateServiceForClient(serviceDescriptorProto, sb);
            }

            sb.AppendLine("}");

            var file = new CodeGeneratorResponse.Types.File
            {
                Name = GetFileName(fileDescriptorProto.Name) + "Client.cs",
                Content = sb.ToString()
            };
            response.File.Add(file);
        }

        private static void GenerateServiceForClient(ServiceDescriptorProto service, StringBuilder sb)
        {
            var serviceId = GetServiceId(service);

            sb.AppendLine($"public abstract class {service.Name}ClientBase : ICRpcGeneratedClient");
            sb.AppendLine("{");
            sb.AppendLine("    public IRpcClient __client = null!;");
            sb.AppendLine();
            sb.AppendLine("    public void BindRpcClient(IRpcClient client)");
            sb.AppendLine("    {");
            sb.AppendLine("        __client = client ?? throw new ArgumentNullException(nameof(client));");

            foreach (var method in service.Method)
            {
                if (!IsServerPush(method))
                {
                    continue;
                }

                ValidateServerPushMethod(service, method);
                var msgId = GetMethodId(service, method);

                sb.AppendLine($"        client.RegisterPushHandler({serviceId}, {msgId}, __OnPush{method.Name}Async);");
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var method in service.Method)
            {
                var msgId = GetMethodId(service, method);

                var outType = GetTypeName(method.OutputType);
                var inType = GetTypeName(method.InputType);

                if (IsServerPush(method))
                {
                    ValidateServerPushMethod(service, method);

                    sb.AppendLine($"    private async CRpcTask __OnPush{method.Name}Async(CRpcPushContext context, byte[] body)");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        await OnPush{method.Name}Async(context, {inType}.Parser.ParseFrom(body));");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                    sb.AppendLine($"    protected virtual CRpcTask OnPush{method.Name}Async(CRpcPushContext context, {inType} message)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        return CRpcTask.CompletedTask(context.Loop);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                    continue;
                }

                sb.AppendLine($"    public async CRpcTask<(int, {outType})> {method.Name}Async({inType} request, int timeOut = 5000)");
                sb.AppendLine("    {");
                sb.AppendLine($"        CRpcMessage message = await __client.CallAsync({serviceId}, {msgId}, request.ToByteArray(), timeOut);");
                sb.AppendLine("        var result = message.getHeader().getResultCode();");
                sb.AppendLine("        if (0 == result)");
                sb.AppendLine("        {");
                sb.AppendLine("            byte[] data = message.getBody();");
                sb.AppendLine($"            return (0, {outType}.Parser.ParseFrom(data));");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        return (-1, null);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
        }

        private static void GenerateServiceForServer(ServiceDescriptorProto service, StringBuilder sb)
        {
            var serviceId = GetServiceId(service);

            var sbMethodParsers = new StringBuilder();
            var sbPushHelpers = new StringBuilder();
            foreach (var method in service.Method)
            {
                var methodId = GetMethodId(service, method);

                var outType = GetTypeName(method.OutputType);
                var inType = GetTypeName(method.InputType);

                if (IsServerPush(method))
                {
                    ValidateServerPushMethod(service, method);
                    sbPushHelpers.AppendLine($"    protected CRpcTask<bool> Push{method.Name}Async(CRpcConnection connection, {inType} message)");
                    sbPushHelpers.AppendLine("    {");
                    sbPushHelpers.AppendLine("        ArgumentNullException.ThrowIfNull(connection);");
                    sbPushHelpers.AppendLine("        ArgumentNullException.ThrowIfNull(message);");
                    sbPushHelpers.AppendLine($"        return connection.SendPushAsync({serviceId}, {methodId}, message.ToByteArray());");
                    sbPushHelpers.AppendLine("    }");
                    sbPushHelpers.AppendLine();
                    continue;
                }

                sbMethodParsers.AppendLine($"        if (methodId == {methodId}) {{ requestParser = {inType}.Parser; responseParser = {outType}.Parser; return true; }}");
            }

            sb.AppendLine($"public abstract class {service.Name}ServiceBase : IRpcService, IRpcHttpJsonCodec");
            sb.AppendLine("{");
            
            sb.AppendLine( "    public ushort GetServiceId()");
            sb.AppendLine( "    {");
            sb.AppendLine($"        return {serviceId};");
            sb.AppendLine( "    }");
            sb.AppendLine();

            var sbMethodCase = new StringBuilder();
            var sbMethodInner = new StringBuilder();
            var sbMethodAbstract = new StringBuilder();
            foreach (var method in service.Method)
            {
                var methodId = GetMethodId(service, method);

                if (IsServerPush(method))
                {
                    ValidateServerPushMethod(service, method);
                    continue;
                }

                var outType = GetTypeName(method.OutputType);
                var inType = GetTypeName(method.InputType);

                sbMethodInner.AppendLine($"    private async CRpcTask<(int, byte[])> __OnMessage{method.Name}Async(CRpcContext context, CRpcMessage req)");
                sbMethodInner.AppendLine("    {");
                sbMethodInner.AppendLine($"        var request = {inType}.Parser.ParseFrom(req.getBody());");
                sbMethodInner.AppendLine($"        var (result, data) = await {method.Name}Async(context, request);");
                sbMethodInner.AppendLine($"        var bytes = data.ToByteArray();");
                sbMethodInner.AppendLine($"        return (result, bytes);");
                sbMethodInner.AppendLine("    }");
                sbMethodInner.AppendLine();

                sbMethodAbstract.AppendLine($"    protected abstract CRpcTask<(int, {outType})> {method.Name}Async(CRpcContext context, {inType} request);");

                sbMethodCase.AppendLine($"        if (methodId == {methodId}) {{ return this.__OnMessage{method.Name}Async(rpcContext, rpcReq); }}");
            }
            
            sb.AppendLine("    public CRpcTask<(int, byte[])> OnMessageAsync(IRpcContext context, IRpcMessage req)");
            sb.AppendLine("    {");
            sb.AppendLine("        var rpcContext = (CRpcContext)context;");
            sb.AppendLine("        var rpcReq = (CRpcMessage)req;");
            sb.AppendLine("        var methodId = rpcReq.getMethodId();");
            sb.Append(sbMethodCase);
            sb.AppendLine("        return CRpcTask.FromResult((-1, Array.Empty<byte>()));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public bool TryGetHttpMethodParsers(ushort methodId, out MessageParser requestParser, out MessageParser responseParser)");
            sb.AppendLine("    {");
            sb.AppendLine("        requestParser = null!;");
            sb.AppendLine("        responseParser = null!;");
            sb.Append(sbMethodParsers);
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.Append(sbMethodInner);
            sb.Append(sbPushHelpers);
            if (sbMethodAbstract.Length > 0)
            {
                sb.Append("    // Please implement the following:");
                sb.AppendLine();
                sb.Append(sbMethodAbstract);
            }

            sb.AppendLine("}");
        }

        private static int GetServiceId(ServiceDescriptorProto service)
        {
            if (!CRpcOptionsReader.TryGetServiceId(service.Options, out var serviceId) || serviceId <= 0)
                throw new Exception("Service=" + service.Name + " ServiceId NOT FOUND");
            if (serviceId >= ushort.MaxValue)
                throw new Exception("Service=" + service.Name + "ServiceId too large");

            return serviceId;
        }

        private static int GetMethodId(ServiceDescriptorProto service, MethodDescriptorProto method)
        {
            if (!CRpcOptionsReader.TryGetMethodId(method.Options, out var methodId) || methodId <= 0)
                throw new Exception("Service" + service.Name + "." + method.Name + " ' MethodId NOT FOUND");
            if (methodId >= ushort.MaxValue)
                throw new Exception("Service" + service.Name + "." + method.Name + " is too large");

            return methodId;
        }

        private static bool IsServerPush(MethodDescriptorProto method)
        {
            return CRpcOptionsReader.TryGetServerPush(method.Options, out var serverPush) && serverPush;
        }

        private static void ValidateServerPushMethod(ServiceDescriptorProto service, MethodDescriptorProto method)
        {
            if (method.OutputType != ".google.protobuf.Empty")
            {
                throw new Exception($"Service {service.Name}.{method.Name} server_push methods must return google.protobuf.Empty");
            }
        }

        private static string GetFileNamespace(FileDescriptorProto protofile)
        {
            var ns = protofile.Options.CsharpNamespace;
            if (string.IsNullOrEmpty(ns))
                throw new Exception("" + protofile.Name + ".proto did not set csharp_namespace");
            return ConvertCamelCase(ns);
        }

        private static string GetFileName(string fileProto)
        {
            var str = fileProto.Split('.')[0];
            return ConvertCamelCase(str);
        }

        private static string ConvertCamelCase(string normalName)
        {
            return string.Join("", normalName.Split('_').Select(s => s.Substring(0, 1).ToUpper() + s.Substring(1)));
        }

        private static string GetTypeName(string typeFullName)
        {
            if (typeFullName.StartsWith(".google.protobuf"))
            {
                return ConvertCamelCase(typeFullName.Split('.').Last());
            }
            //TODO: optimize
            // .gameserver.AaBbCc -> GameServer.AaBbCc
            string str = typeFullName.Substring(1, 1).ToUpper() + typeFullName.Substring(2);
            return str;
        }
}